version: '2.1'
services:
  frontend:
    build: .
    image: frontend
    container_name: ticket
    hostname: ticket
    ports:
      - "3000:3000"
    networks:
      - frontendnet
networks:
  frontendnet: